version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      
      # Install dependencies needed for running tests
      - cd ng-crossroads
      - npm install
      - npm install -g @angular/cli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
  build:
    commands:
      - ng build
  post_build:
    commands:
      # # Remove existing node_modules to clear dev dependencies
      # - rm -r node_modules

      # # Install runtime dependencies
      # - npm install --production

      # - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  # type: zip
  files:
    - '**/*'
